//
//  Summary.swift
//  messageAI
//
//  AI-generated conversation summary model
//

import Foundation

/// Summary of a conversation thread
/// Generated by AI from conversation messages
struct Summary: Codable, Identifiable {
    let id: String
    let conversationId: String
    let summary: String              // Full summary text
    let keyPoints: [String]          // Bullet points of key information
    let messageCount: Int            // Number of messages summarized
    let timeRange: TimeRange?        // Time range of messages
    let participants: [String]       // Participant names
    let generatedAt: Date           // When summary was generated

    /// Time range for summarized messages
    struct TimeRange: Codable {
        let start: Date
        let end: Date
    }

    /// Initialize a summary from Cloud Function response
    init(
        id: String = UUID().uuidString,
        conversationId: String,
        summary: String,
        keyPoints: [String],
        messageCount: Int,
        timeRange: TimeRange?,
        participants: [String],
        generatedAt: Date = Date()
    ) {
        self.id = id
        self.conversationId = conversationId
        self.summary = summary
        self.keyPoints = keyPoints
        self.messageCount = messageCount
        self.timeRange = timeRange
        self.participants = participants
        self.generatedAt = generatedAt
    }
}
